# This file was generated by GoReleaser. DO NOT EDIT.
cask "llml" do
  name "llml"
  desc "Terminal UI to discover local LLMs and launch llama.cpp, vLLM, Ollama, or MLX"
  homepage "https://github.com/flyingnobita/llml"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llml"

  on_macos do
    on_intel do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b05d8722afb0525c62369209416fd2f5d94a362552c8b3a625fe5a6f031aa1b9"
    end
    on_arm do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_arm64.tar.gz"
      sha256 "4a3847783773da0f88fd0e0a1edc638c8d180a306a4b78ed25d26d7f0899a27d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_x86_64.tar.gz"
      sha256 "737ea9ae00a50dffcaaafef360277393437521ede1b634adfc03ea9c6ae5a3a8"
    end
    on_arm do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_arm64.tar.gz"
      sha256 "f957f3ed3c801423006aa4b5ee9f4f146ca19819680a3232e17ff5e4d10ddbb1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llml"]
    end
  end

  # No zap stanza required
end
