# This file was generated by GoReleaser. DO NOT EDIT.
cask "llml" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "3bd5c5bb757dcc22fc8b93181229a213cfd8fc39eb38de988969da6c3ea5f09f"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9ad3e28b1c4cfaf2b04652888216d27c523630e3502619e638b436a19aad8d70"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d153610d09a718bfdf5d333c0cbaa61d92ce694a45feb0f0289e396f1ca1f7a4"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "02a8146012ff5e27127f2976e0b118fe91eb20cb048995eca5124c1a849e0f42"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "llml"
  desc "Terminal UI to discover local models and launch llama-server, vLLM, or Ollama"
  homepage "https://github.com/flyingnobita/llml"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llml"

  # No zap stanza required

end
