# This file was generated by GoReleaser. DO NOT EDIT.
cask "llml" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "e41abe4aa5804792708810c83fc096dd396dc843176739141201d50a11e720f9"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d7aafd6fdb510aeb334622bf59b5d3a81d5c2abf4477106bb1baf377fcb40140"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2894d7de7850daf1b5b36dd4839dfd25cb4004df9f8bc28ef82eb061b01ca8f"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a1696b3c3e9b09ec14e30dba2d56918616c52b60b291d1148338371fb353c0db"
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "llml"
  desc "Terminal UI to discover local models and launch llama-server, vLLM, or Ollama"
  homepage "https://github.com/flyingnobita/llml"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llml"

  # No zap stanza required

end
