# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llml < Formula
  desc "Terminal UI to discover local models and launch llama-server, vLLM, or Ollama"
  homepage "https://github.com/flyingnobita/llml"
  version "0.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.8/llml_0.2.8_Darwin_x86_64.tar.gz"
      sha256 "a3c38fb46733b73958727f718489208a08ceeaefff8c8987bd97856f4e73aa38"

      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.8/llml_0.2.8_Darwin_arm64.tar.gz"
      sha256 "275f2ea4a5e138ef82ac375d2322d526ce301ef8775154ee17e9aac8049ce1d3"

      define_method(:install) do
        bin.install "llml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.8/llml_0.2.8_Linux_x86_64.tar.gz"
      sha256 "aa79dac58e485fe7fb6f954c025b9d77b405096171c67482e3620578b1605f11"
      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.8/llml_0.2.8_Linux_arm64.tar.gz"
      sha256 "2695c15bfa6ddb861484eb6d90d6a9d6a3c6323e80b88c47742cd73cf5352f30"
      define_method(:install) do
        bin.install "llml"
      end
    end
  end
end
